name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        uses: fatjyc/push-gcr-action@6ba6a5ae173e339c471992cf20077a1afe86062e
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
