name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        uses: fatjyc/push-gcr-action@4128f4d93784f26f63eb83baae034ea67510ed71
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
