name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo ${{ github.event.repository.default_branch }}
          echo ${{ github.ref }}
          echo ${{ format('refs/heads/{0}', ) }}
          echo ${{ format('refs/heads/{0}', ) == github.ref }}
          
          
      - name: Build and push Docker images to Github Container Registry
        # You may pin to the exact commit or the version.
        # uses: fatjyc/push-gcr-action@5e1e8131d5ef5b274313d315c29de3d478d515a7
        uses: fatjyc/push-gcr-action@5e87014a646d9f3c445ef818c171ceac12d2d824
        with:
          user: fatjyc
          token: ${{ secrets.GH_TOKEN }}
          tagUseBranchNameWhenPush: true
