name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        uses: fatjyc/push-container-registry-action@8cc72408434e33abf00791268c8ee2b6d984effb
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
