name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        uses: fatjyc/push-gcr-action@0545c420a3a83f4a66f9be339be7ef117bb017fd
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
