name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        uses: fatjyc/push-gcr-action@884fdc22acba83157416c81592655ced1fee7cb1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
