name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        uses: fatjyc/push-gcr-action@52c88d711e3328be0005847ff25adc2381593d58
        with:
          user: fatjyc
          token: ${{ secrets.GH_TOKEN }}

