name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        uses: fatjyc/push-gcr-action@6a46222d63321702c5bc8d25ead2367c469646ab
        with:
          user: fatjyc
          token: ${{ secrets.GH_TOKEN }}

