name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        uses: fatjyc/push-gcr-action@dc3ac37695bce7d4eb1f0b8f9b09523fd48aa4bd
        with:
          user: fatjyc
          token: ${{ secrets.GH_TOKEN }}

