name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        uses: fatjyc/push-gcr-action@ef467e111965e1e19f64b06079b2023e3a35d223
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
