name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        uses: fatjyc/push-gcr-action@efd038d7e5054494c37b22c49fe6e980f1f9d814
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
