# This is a basic workflow to help you get started with Actions

name: Update Submodule

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    branches: main
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: update submodule
        uses: fatjyc/update-submodule-action@541b7a3f2cabfe107ec5ff953572bfe030c66e2b
        with:
          user: fatjyc
          token: ${{ secrets.GH_TOKEN }}
          repo_owner: fatjyc
          repo: submodule-demo
          committor_username: xxx
          committor_email: xxx@xxx.com
          target_branch: main
          path: ${{ github.repo.repo }}
          
